defaults: &defaults
  working_directory: /tmp/dashboard
  docker:
    - image: circleci/node:10

version: 2
jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: /tmp
          paths:
            - dashboard

  build_client:
    <<: *defaults
    environment:
      NODE_ENV: production
    working_directory: /tmp/dashboard/client

    steps:
      - attach_workspace:
          at: /tmp

      - run: yarn build

      - store_artifacts:
          path: /tmp/dashboard/client/build
          destination: client-build-artifacts

workflows:
  version: 2
  client:
    jobs:
      - install
      - build_client:
          requires:
            - install
