version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    working_directory: ~/dashboard

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  build:
    docker:
      - image: circleci/node:10
    environment:
      NODE_ENV: production
      CI: true
    working_directory: ~/dashboard

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-

      - run: cd client
      - run: yarn build

      - store_artifacts:
          path: /tmp/client-artifacts
          destination: client-build-artifacts

workflows:
  version: 2
  client:
    jobs:
      - install
      - build:
          requires:
            - install
